In [2]:
import numpy as np

In [11]:
myarr=np.array([3,6,35,77777,85],np.int8) #8 bit integer generally it was 32 bit integers
myarr

array([  3,   6,  35, -47,  85], dtype=int8)

In [7]:
myarr[2]

35

In [8]:
myarr.shape

(5,)

In [9]:
myarr.dtype

dtype('int8')

In [10]:
myarr[3]=125
myarr

array([  3,   6,  35, 125,  85], dtype=int8)

# Array creation: Conversion from other Python structure

In [12]:
listarray=np.array([[1,2,3],[4,5,6],[7,8,9]])
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
listarray.dtype

dtype('int32')

In [15]:
zeros=np.zeros((2,5))  #create 0 array
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
rng = np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
lspace=np.linspace(1,50,10)  #10 elements bet 1 to 50 equally spaced
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [20]:
emp=np.empty((4,6)) #array 4x6 with random elements
emp

array([[2.56761491e-312, 2.41907520e-312, 1.29441743e-312,
        2.37663529e-312, 2.05833592e-312, 2.41907520e-312],
       [2.56761491e-312, 1.93101617e-312, 9.33678148e-313,
        9.33678148e-313, 1.12465777e-312, 1.16709769e-312],
       [1.16709769e-312, 1.16709769e-312, 1.18831764e-312,
        1.97345609e-312, 2.33419537e-312, 9.76118064e-313],
       [2.33419537e-312, 1.18831764e-312, 2.12199579e-313,
        2.56761491e-312, 2.41907520e-312, 2.56761491e-312]])

In [21]:
emp_like=np.empty_like(lspace)
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [22]:
ide=np.identity(50) # identity matrix of 50X50
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [23]:
arr=np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [24]:
arr.reshape(3,33)   #change shape but original does not change

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [28]:
arr=arr.reshape(3,33)  # now original changed
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [27]:
arr.ravel() # back to original

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [29]:
ar=np.array([[1,2,3],[4,5,6],[7,1,0]])
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [31]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [33]:
ar.flat

In [34]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [35]:
ar.ndim      #dimention

2

In [37]:
ar.size  

9

In [38]:
ar.nbytes    #total bytes

36

In [41]:
one =np.array([1,3,4,85,96,147,2,6,1])  #index of max element
one.argmax()

5

In [42]:
one.argsort()   #sorted array indexes

array([0, 8, 6, 1, 2, 7, 3, 4, 5], dtype=int64)

In [44]:
ar.argmax()  #it makes 2D to 1D then return index 

array([2, 1, 1], dtype=int64)

In [47]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [48]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [50]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [51]:
ar2=np.array([[1,2,1],[4,0,6],[8,1,0]])
ar+ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [52]:
ar*ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [53]:
ar/ar2

C:\Users\parth\AppData\Local\Temp\ipykernel_4652\2166607628.py:1: RuntimeWarning: divide by zero encountered in divide
  ar/ar2
C:\Users\parth\AppData\Local\Temp\ipykernel_4652\2166607628.py:1: RuntimeWarning: invalid value encountered in divide
  ar/ar2


array([[1.   , 1.   , 3.   ],
       [1.   ,   inf, 1.   ],
       [0.875, 1.   ,   nan]])

In [54]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [55]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [56]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [57]:
np.count_nonzero(ar)

8

In [58]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [59]:
import sys
py_ar=[0,4,55,2]
np_ar=np.array(py_ar)
sys.getsizeof(1)*len(py_ar)

112

In [60]:
np_ar.itemsize*np_ar.size

16

In [61]:
np_ar.tolist()

[0, 4, 55, 2]